### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by alexgleason** [RackhamLeNoir/gamebuino-bangbang#1]
Hi, I'm currently in the process of adding license info to all the games in [Erwin's Arduboy repo](http://arduboy.ried.cl/) so people can easily filter out proprietary games. Would you be willing to add an [open source license](https://choosealicense.com/) to your project so I can tag it as an open source game in the repo?

Thanks!

**Comment by ThomasPietrzak** [comment]
Hi,

You are right. I just added a GPLv3 licence. I also added it to my two other games: 
https://github.com/RackhamLeNoir/gamebuino-jezzball/tree/master
https://github.com/RackhamLeNoir/gamebuino-taquin/tree/master

Cheers,

**Comment by alexgleason** [comment]
Thanks!
